"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['go.py']
DATA_FILES = ['images/icon.icns']
OPTIONS = {'iconfile': 'images/icon.icns'}

setup(name="Mouse Sniper",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
